  CREATE TABLE DROOL_ALERT
   (	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	tradeId NUMBER(10),
	 PRIMARY KEY (id)
);

  CREATE TABLE DROOL_DATA
   (	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	userId NUMBER(10),
	tradeAmount NUMBER(10),
	 PRIMARY KEY (id)
);

INSERT into drool_data (userId, tradeAmount) VALUES (2, 8);
INSERT into drool_data (userId, tradeAmount) VALUES (45, 7);
INSERT into drool_data (userId, tradeAmount) VALUES (64, 4);
INSERT into drool_data (userId, tradeAmount) VALUES (12, 6);
INSERT into drool_data (userId, tradeAmount) VALUES (22, 11);
INSERT into drool_data (userId, tradeAmount) VALUES (7, 3);
INSERT into drool_data (userId, tradeAmount) VALUES (93, 7);
INSERT into drool_data (userId, tradeAmount) VALUES (41, 14);

commit;